### PR TITLE
Feature/6 27 31 services field

### PR DESCRIPTION
**Pull request by ekes**
* Provides new `localgov_services_parent` field. This replaces fields mentioned in overview #27.
 * Field (autocomplete) selection and label display include the hierarchy for sublanding pages.
 * Field tested as deployed, but also added to content type not necessarily in Services: 'opt-ing in'.
 * Adds and tests path auto and breadcrumbs for the content type based on the hierarchy.

### CODE REVIEW

**Comment by ekes** [comment]
Follow-up separate issue for form field placement #35

**Comment by stephen-cox** [comment]
Hi @ekes, This looks to work well for me. I fixed a few minor coding standard and deprecation errors. Shall I merge this or would you like for @finnlewis to review as well?

**Comment by finnlewis** [comment]
Hi @ekes @stephen-cox 

I'm testing this locally and I'm seeing test failures on Drupal\Tests\localgov_core\Functional\Block. 

I created a branch at https://github.com/localgovdrupal/localgov/tree/feature/6-27-31-services-field

Then switched the composer.json in the root profile to use 

`"localgovdrupal/localgov": "dev-feature/6-27-31-services-field"`

Then the full rebuild and re-install

```
rm -rf web/profiles/contrib/ web/modules/contrib/; 
composer clear-cache; composer update --with-dependencies --no-cache;
lando start;
lando drush si localgov -y;
```
Then running lando phpunit I see this: 
```

Summary of non-successful tests:

Drupal\Tests\localgov_core\Functional\Block
 ✘ Blocks display
   │
   │ Behat\Mink\Exception\ExpectationException: Current response status code is 404, but 200 expected.
   │ 
   │ /app/vendor/behat/mink/src/WebAssert.php:768
   │ /app/vendor/behat/mink/src/WebAssert.php:130
   │ /app/web/modules/contrib/localgov_core/tests/src/Functional/BlockTest.php:73
   │ 

Drupal\Tests\localgov_services_navigation\FunctionalJavascript\EntityReferenceServicesAutocomplete
 → Services entity reference autocomplete widget
 → Entity reference autocomplete widget
 → Entity reference sublanding label widget
```

**Comment by finnlewis** [comment]
I just tested again rebuilding from master, and the tests do pass, so it does appear to be related to this branch @ekes

**Comment by andybroomfield** [comment]
Seeing the same when I run the tests against this branch.

**Comment by ekes** [comment]
@finnlewis @andybroomfield 

With this fix for the block test localgovdrupal/localgov_core#8 ?

**Comment by andybroomfield** [comment]
I just ran the test and Blocks Display and Blocks display no title passed.
I see warnings the following are risky tests
 → Services entity reference autocomplete widget
 → Entity reference autocomplete widget
 → Entity reference sublanding label widget

**Comment by ekes** [comment]
@andybroomfield :-
> I see warnings the following are risky tests

For that you need, localgovdrupal/localgov_project#15 which looks like it's merged, so that and a `lando rebuild` to pull the new image and spin up the chromedriver container.

**Comment by ekes** [comment]
OK I'm assuming this is good to go with the related test fixed.

**Pull request merged**
