### PR TITLE
[#165] Removed condition_field patches in composer.json

### LINKED ISSUE #165: The drupal/condition_field patches failed to apply
Currently, the drupal/condition_field patches are blocking update/install with composer:

Screenshot 2022-06-01 at 15 10 19

Suggestion: Remove the patches from composer.json because the new version of drupal/condition_field module has already applied these changes from the patches.

### PR DESCRIPTION
**Pull request by tran-bigbluedoor**
Fixed: https://github.com/localgovdrupal/localgov_services/issues/165

### CODE REVIEW

**Review by andybroomfield — APPROVED** [review]
Looks good, thanks @tran-bigbluedoor

**Comment by finnlewis** [comment]
Great, thanks @tran-bigbluedoor ! Hope to get this merged and a new release later today at our Merge Monday meeting at 2pm.

**Comment by louwrense** [comment]
Thank you @andybroomfield @finnlewis. That would be amazing, thank you. We have several LocalGov deployments that are currently failing due to this issue, so it would be great to have this blocker resolved as soon as possible. Thank you for your help. :)

**Comment by stephen-cox** [comment]
I've merged this PR as I was hitting the same issue and this fixes that. Let's get a release out later today

**Pull request merged**
