### PR TITLE
Add cache tags for all status nodes to service status message block

### LINKED ISSUE #229: Deleted service status updates only disappear from landing page after a cache rebuild
I haven't been able to fully test this yet but I believe that modules/localgov_services_status/localgov_services_status.module should include an implementation of `hook_ENTITY_TYPE_predelete()` so that the landing page cache is invalidated when a status is deleted in same way as it is in the implementation of `hook_ENTITY_TYPE_presave()` when a status page is saved.

### PR DESCRIPTION
**Pull request by stephen-cox**
Fixes #229

### CODE REVIEW

**Comment by finnlewis** [comment]
@dedavidson are you able to test this and see if it works for you?

**Comment by finnlewis** [comment]
Would like someone to manually test this.

**Comment by dedavidson** [comment]
Will get this tested - sorry trying to clear decks before Xmas!

**Comment by ekes** [comment]
Hopefully we can get this merged next MT?

I kinda wish I hadn't looked. But I did and the update https://github.com/localgovdrupal/localgov_services/pull/234/commits/f4d7c12c12cbf27b3ef994aeb490628e26aac0de should make it even closer to correct, even though I can't quite get the tests to play for all the variations.

Also should we manually drop 9.4 from the test matrix? Or should it be done with the script?

**Comment by ekes** [comment]
Bump for MT (also rerunning tests).

**Comment by finnlewis** [comment]
@ekes is happy! :smile:

**Pull request merged**
