### PR TITLE
Add default configuration for simple_sitemap for each content type in…

### PR DESCRIPTION
**Pull request by finnlewis**
… the localgov_services module.

Depends on https://github.com/localgovdrupal/localgov/pull/50

### CODE REVIEW

**Comment by finnlewis** [comment]
Looks like the tests are failing, with 
"Drupal\Core\Config\Schema\SchemaIncompleteException: No schema for simple_sitemap.bundle_settings.default.node.localgov_services_page"

**Comment by ekes** [comment]
I'm confused. This configuration was in optional. It's not like you _must_ have simple sitemap for the module. Admittedly with this module we can't see much point in installing it without the profile where simplesite map is enabled, but it still doesn't need to be installed?

**Comment by finnlewis** [comment]
I think that it is a sensible default to have a sitemap.xml generated. 

This module depends on localgov_core, which enables simple_sitemap, so we might as well set sensible defaults.

I saw the configuration was in optional, which confused me as 1) it was already there and 2) it didn't install, so I moved it to install. I'd like to understand why it didn't work in optional, but I still think it should be installed by default. 

If you strongly disagree, maybe we should seek more opinions?

**Comment by finnlewis** [comment]
Oh, sorry, I'm getting confused between the localgov_core and the localgov profile... I see your point that this might be installed without the profile.

**Comment by finnlewis** [comment]
@ekes just looking at this again to try to get the config to install optionally. Could you point me back to the example where the install profile or somewhere checks for optional config to help if modules are enabled in the wrong order?

**Comment by finnlewis** [comment]
So now this PR has evolved into just removing the config/optional config for simple_sitemap, as it is now in the profile, pending on https://github.com/localgovdrupal/localgov/pull/50/files?file-filters%5B%5D=

**Comment by finnlewis** [comment]
@stephen-cox added default config for services_status content type in hook_install. Tested locally and does what's expected.

**Pull request merged**
