### PR TITLE
Fix: Unpublished link in Subservice page

### PR DESCRIPTION
**Pull request by Adnan-cds**
Links for unpublished pages should not be listed at all in Service sublanding pages.  At the moment, unpublished child pages are occupying an empty slot. This is particularly visible when the localgov_base theme is in use.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Thanks for looking @Adnan-cds.
With regard to the deprecated getImplementation, see #174, I think we need to wait until Drupal 9.3 is end of life and then set the minimum Drupal core version to 9.4.

**Comment by Adnan-cds** [comment]
> With regard to the deprecated getImplementation, see https://github.com/localgovdrupal/localgov_services/pull/174, I think we need to wait until Drupal 9.3 is end of life and then set the minimum Drupal core version to 9.4.

Sounds like a good idea.  Or should we do a new minor release which requires Drupal 9.4+?

This pull request has been really puzzling.  Tests run fine in my machine, but not here.  Can't think of why this may be happening :(

**Comment by andybroomfield** [comment]
Otherwise this works for me @Adnan-cds, so we just need to decide if we want to include the deprecation fix here or wait until #174 and get the unpublished page fix in as stand alone.

**Comment by Adnan-cds** [comment]
> Otherwise this works for me

Thanks for trying this Andy :)

> so we just need to decide if we want to include the deprecation fix here or wait until #174 

I would suggest fixing the deprecation issues either here or in #174 and also to tell composer.json to require drupal/core: ^9.4.  The localgov_openreferral module is [already doing that for ^9.1](https://github.com/localgovdrupal/localgov_openreferral/blob/5cd9c34965b84bc3909a192ce0de24787869508d/composer.json#L8).

> and get the unpublished page fix in as stand alone.

I can now confirm that PHPUnit tests are failing for localgov_services.  I have raised a draft pull request with no code changes and the FunctionalJavascript tests still [failed](https://github.com/localgovdrupal/localgov_services/pull/179/checks) :(  These tests run fine in my local machine under PHP 7.4, so I can't say why this is failing in the Github test runner.

So yes, as you have said, we have two options with this pull request:
- Accept it with the deprecation fixes plus requiring drupal/core ^9.4 in composer.json.  FunctionalJavascript tests still fail in the Github test runner.
- Accept it without the deprecation fixes.  FunctionalJavascript tests fail in the Github test runner.  The upside here is that Drupal 9.3 sites can then enjoy this fix.

Let's discuss these in the next Merge Monday meeting.

**Review by andybroomfield — APPROVED** [review]
I'm happy to see these changes merged.

**Comment by Adnan-cds** [comment]
Thanks Andy.  Merging...

**Pull request merged**
