### PR TITLE
Refactor service page blocks

### PR DESCRIPTION
**Pull request by stephen-cox**
As part of refactoring the templates for the service pages (localgovdrupal/localgov_theme/issues/15) the blocks displaying service page fields in different page regions needed fixing up.

This doesn't show the automatically created related links from topics as I believe this functionality hasn't been fully specified yet: https://github.com/localgovdrupal/localgov_services/blob/feature/34-refactor-service-blocks/modules/localgov_services_page/src/Plugin/Block/ServicesRelatedLinksBlock.php#L30

### CODE REVIEW

**Comment by andybroomfield** [comment]
Have installed this branch with demo content to see the layout.
Verifiyed that the fields are now displaying approbriate content.
Screenshot_2020-06-08 Test Service Drush Site-Install
These are on the service landing page. These links (common tasks) should be below title, in the content area.
Eg. BHCC Rubbish recycling page:
Screenshot 2020-06-08 at 2 39 43 pm

Verified that the list of service pages is now displaying on landing page, however they are unlinked.
Screenshot_2020-06-08 Service sub-landing test Drush Site-Install

Verified that I see the related links and topics on a service page. There placement is at the bottom rather than the right on BHCC, though I assume that is more of a template issue.

Screenshot_2020-06-08 Service page Drush Site-Install

**Comment by andybroomfield** [comment]
This is the code that appears to generate the automated related links based on topics on the BHCC site. Its in a field formatter in the bhcc_service_info module.
````php
  /**
   * Automatically builds a list of links based on the most relevant pages.
   *
   * @return array
   */
  private function buildAutomated() {
    // Convert topics field into an array we can use in the query.
    $topics = [];

    foreach ($this->getTopics() as $topic) {
      $topics[] = $topic->id();
    }

    if ($topics) {
      // Perform our query.
      $query = $this->database->query('SELECT entity_id FROM node__field_all_topics
  LEFT JOIN node_field_data ON node_field_data.nid=node__field_all_topics.entity_id
  WHERE node__field_all_topics.entity_id != :nid
  AND node__field_all_topics.field_all_topics_target_id IN (:tids[])
  AND node_field_data.status=1
  GROUP BY node__field_all_topics.entity_id
  ORDER BY count(*) desc
  LIMIT 6;',
        [
          ':nid' => $this->node->id(),
          ':tids[]' => $topics,
        ]
      );

      $list = [];
      foreach ($query->fetchAll() as $result) {
        $node = Node::load($result->entity_id);
        $list[] = [
          'title' => $node->getTitle(),
          'url' => $node->toUrl(),
        ];
      }

      return $list;
    }

    return [];
  }
````

**Comment by ekes** [comment]
> This is the code that appears to generate the automated related links based on topics 

I guess we're parking the topic stuff until the review next week?

**Comment by andybroomfield** [comment]
@ekes I guess so. Wasn't sure as it was mentioned in the PR post.

**Comment by ekes** [comment]
Added an issue for them, there's also the TODO linked in the code in the intro.

**Comment by ekes** [comment]
Erm... it's merged‽

**Pull request closed without merging**
