### PR TITLE
Run tests using GitHub Actions on pull requests

### PR DESCRIPTION
**Pull request by stephen-cox**
This adds coding standard and deprecation checks and runs tests to the services repo. There's only a little change from the checks here https://github.com/localgovdrupal/drupal-container/blob/master/.github/workflows/ci.yml

As you can see, the coding standards checks currently fail.

### CODE REVIEW

**Comment by finnlewis** [comment]
This looks cool! 
Do we need to fix the code tests to merge it?

**Comment by stephen-cox** [comment]
It doesn't do JS tests yet. There's an issue for this here: https://github.com/localgovdrupal/drupal-container/issues/1

We might want to set things so that it runs all checks and tests and then fails - at the moment it runs coding standards, then deprecated code and then tests - it stops at the first failure - which is coding standards.

**Comment by stephen-cox** [comment]
JS tests are now running as https://github.com/localgovdrupal/drupal-container/issues/1 if fixed.

There are still coding standards and deprecated code errors. The services related errors will be fixed with: https://github.com/localgovdrupal/localgov_services/pull/48

**Comment by finnlewis** [comment]
Nice one @stephen-cox 

I guess we should fix the coding standards quickly before coming back to this to confirm and merge.

**Comment by finnlewis** [comment]
This looks like the tests are now passing, so let's merge this one in and start letting the machines do the work!

**Comment by stephen-cox** [comment]
There are still occasional failures which seem to be due to the environment and not the related to our tests. See https://github.com/localgovdrupal/localgov_core/runs/779473268

These need addressing so this was still marked as a in progress, but we'll have to see how often this sort of thing crops up

**Pull request merged**
